image: fedora:rawhide
stages:
  - build

variables:
  DEPENDENCIES: libusb1-devel glib2-devel nss-devel pixman-devel systemd meson gtk-doc
                gcc gcc-c++ glibc-devel libX11-devel libXv-devel gtk3-devel


before_script:
  - dnf update -y --nogpgcheck && dnf install -y --nogpgcheck $DEPENDENCIES


build:
  stage: build
  script:
    # Build with a driver that doesn't need imaging, or nss
    - meson -Ddrivers=elan . _build
    - ninja -C _build
    - rm -rf _build/
    # And build with everything
    - meson -Ddrivers=all . _build
    - ninja -C _build
    - ninja -C _build install

